/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    BackButton: typeof import('./src/components/business/back-button/BackButton.vue')['default']
    Bubble: typeof import('./src/components/business/bubble/Bubble.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Chat: typeof import('./src/components/business/chat/Chat.vue')['default']
    Composer: typeof import('./src/components/business/composer/Composer.vue')['default']
    copy: typeof import('./src/components/business/quick-replies/QuickReplies copy.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Message: typeof import('./src/components/business/message/Message.vue')['default']
    MessageContainer: typeof import('./src/components/business/message-container/MessageContainer.vue')['default']
    ModelSelector: typeof import('./src/components/ModelSelector.vue')['default']
    Navbar: typeof import('./src/components/business/navbar/Navbar.vue')['default']
    NavBar: typeof import('./src/components/business/navbar/NavBar.vue')['default']
    QuickReplies: typeof import('./src/components/business/quick-replies/QuickReplies.vue')['default']
    QuickReply: typeof import('./src/components/business/quick-replies/QuickReply.vue')['default']
    SystemMessage: typeof import('./src/components/business/system-message/SystemMessage.vue')['default']
    Time: typeof import('./src/components/business/time/Time.vue')['default']
  }
}
